server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: ServiceBack
          uri: lb://ServiceBack
          predicates:
            - Path=/back/**
        - id: ServiceAuth
          uri: lb://ServiceAuth
          predicates:
            - Path=/auth/**
        - id: ServiceMobile
          uri: lb://ServiceMobile
          predicates:
            - Path=/mobile/**
      x-forwarded:
        enabled: false
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"

