server:
  port: 8002
  servlet:
    context-path: /due/back
due:
  resource:
    auth:
      authAddress: http://localhost:8001/due/auth/token/convert # 认证服务器地址
      ignoreUrls:                                               # 不需要登录就可以访问的url
        - /system/role/list
feign:
  okhttp:
    enabled: true
logging:
  level:
       com:
         due:
           cloud:
             rpc: debug